config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    member do
      put :publish
      put :unpublish
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  def set_published_status(status)
    update(published: status)
  rescue ActiveRecord::RecordInvalid => e
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  
    def index
      @posts = Post.all
    end
  
    def show
    end
  
    def new
      @post = Post.new
    end
  
    def create
      @post = Post.new(post_params)
  
      if @post.save
        redirect_to posts_path, notice: 'Post created!'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @post.update(post_params)
        redirect_to posts_path, notice: 'Post updated!'
      else
        render :edit
      end
    end
   
  
    def destroy
      @post.destroy
      redirect_to posts_path, notice: 'Post deleted!'
    end
  
    def publish
      if @post.set_published_status(true)
        redirect_to posts_path, notice: 'Post published!'
      else
        flash.now[:error] = 'Error publishing post'
        render :show
      end
    end
    
    def unpublish
      if @post.set_published_status(false)
        redirect_to posts_path, notice: 'Post unpublished!'
      else
        flash.now[:error] = 'Error unpublishing post'
        render :show
      end
    end
    
  
    private
  
    def post_params
    params.require(:post).permit(:title, :content, :published)
  end
 
  
   
  end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= notice %> 
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_with model: @post do |form| %>
  <%= form.text_field :title %>
  <%= form.text_field :content %>
  <%= form.check_box :published %>
  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<h2>Post Crud</h2>
<%= link_to 'Add', new_post_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.published ? 'Yes' : 'No' %></td>
        <td>
          <% if post.published %>
            <%= link_to 'Unpublish', unpublish_post_path(post), class: 'unpublish-link', method: :put %>
          <% else %>
            <%= link_to 'Publish', publish_post_path(post), class: 'publish-link', method: :put %>
          <% end %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New</h1>

<% if @post.errors.any? %>
    <%= @post.errors.full_messages %>
<% end %>

<%= form_for @post do |form| %>
    
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :content %>
    <%= form.text_field :content %>

    <%= form.check_box :published %>
    <%= form.submit 'Create Post'%>
 <% end %>